#   ____                   _    
#  |  _ \    ___   __  __ (_)   
#  | |_) |  / _ \  \ \/ / | |   
#  |  _ <  | (_) |  >  <  | |   
#  |_| \_\  \___/  /_/\_\ |_|   
#         C O N F I G
#


plugins:
  - routify
  - rollup
  - nollup:
      port: 5000
  - spassr:
      port: 5005
      ssr: true
  - "@roxi/plugin-postcss"
  - "@roxi/plugin-mdsvex"
  - debugger
    # layout: src/components/layout.svelte
