#   ____                   _    
#  |  _ \    ___   __  __ (_)   
#  | |_) |  / _ \  \ \/ / | |   
#  |  _ <  | (_) |  >  <  | |   
#  |_| \_\  \___/  /_/\_\ |_|   
#         C O N F I G
#


plugins:
  # local plugin/user config. Parameters will passed to the plugin
  - _roxi/custom.plugin.js:
      foo: 'bar'
  
  # builtin plugins
  - routify
  - rollup
  - nollup:
      port: 5000
  - spassr:
      port: 5005
      ssr: true
  - postcss
  - mdsvex
    # layout: src/components/layout.svelte
  - debugger
